"use client";
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import {
    FileText, CheckCircle, AlertTriangle, XCircle,
    Loader2, ArrowLeft, Download, Brain,
} from "lucide-react";
import { api, formatCrore } from "@/lib/api";
import Link from "next/link";

export default function CAMPage() {
    const { id } = useParams<{ id: string }>();
    const [cam, setCam] = useState<any>(null);
    const [company, setCompany] = useState<any>(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState("");

    useEffect(() => {
        Promise.all([
            api.get(`/api/cam/${id}`),
            api.get(`/api/companies/${id}`),
        ])
            .then(([camRes, compRes]) => {
                setCam(camRes.data);
                setCompany(compRes.data);
            })
            .catch((e) => setError(e?.response?.data?.detail || "Failed to load CAM report"))
            .finally(() => setLoading(false));
    }, [id]);

    if (loading) {
        return (
            <div className="flex items-center justify-center min-h-[60vh] gap-3">
                <Loader2 className="w-6 h-6 text-brand-400 animate-spin" />
                <span className="text-slate-400">Loading CAM report...</span>
            </div>
        );
    }

    if (error) {
        return (
            <div className="max-w-lg mx-auto px-6 py-20 text-center">
                <XCircle className="w-12 h-12 text-red-400 mx-auto mb-4" />
                <h2 className="text-xl font-bold mb-2">CAM Report Not Found</h2>
                <p className="text-slate-400 text-sm mb-6">{error}</p>
                <Link href="/upload" className="btn-primary inline-flex gap-2 items-center">
                    <ArrowLeft className="w-4 h-4" /> Upload Document
                </Link>
            </div>
        );
    }

    const decisionColor =
        cam?.decision === "Approve" ? "text-emerald-400" :
            cam?.decision?.includes("Condition") ? "text-amber-400" :
                "text-red-400";

    const decisionIcon =
        cam?.decision === "Approve" ? <CheckCircle className="w-6 h-6 text-emerald-400" /> :
            cam?.decision?.includes("Condition") ? <AlertTriangle className="w-6 h-6 text-amber-400" /> :
                <XCircle className="w-6 h-6 text-red-400" />;

    const sections = [
        { title: "Executive Summary", content: cam?.executive_summary, icon: Brain },
        { title: "Company Overview", content: cam?.company_overview, icon: FileText },
        { title: "Financial Analysis", content: cam?.financial_analysis, icon: FileText },
        { title: "Risk Assessment", content: cam?.risk_assessment, icon: AlertTriangle },
        { title: "Industry Outlook", content: cam?.industry_outlook, icon: FileText },
        { title: "Loan Recommendation", content: cam?.loan_recommendation, icon: CheckCircle },
    ];

    return (
        <div className="max-w-4xl mx-auto px-6 py-10 space-y-8 animate-in">
            {/* Header */}
            <div>
                <Link
                    href={`/analysis/${id}`}
                    className="flex items-center gap-1.5 text-slate-400 hover:text-white text-sm mb-4 transition-colors"
                >
                    <ArrowLeft className="w-3.5 h-3.5" /> Back to Analysis
                </Link>

                <div className="glass rounded-2xl p-6">
                    <div className="flex items-start justify-between gap-4 flex-wrap">
                        <div>
                            <div className="text-xs text-slate-500 font-semibold uppercase tracking-wider mb-1">
                                Credit Appraisal Memo
                            </div>
                            <h1 className="text-2xl font-black text-white">
                                {company?.company_name || "Company"}
                            </h1>
                            <p className="text-xs text-slate-500 mt-1">
                                Generated by IntelliCredit AI · {new Date(cam?.generated_at || Date.now()).toLocaleDateString("en-IN", { dateStyle: "long" })}
                            </p>
                        </div>
                        <div className="text-right">
                            <div className="flex items-center gap-2 justify-end mb-1">
                                {decisionIcon}
                                <span className={`text-xl font-black ${decisionColor}`}>{cam?.decision}</span>
                            </div>
                            <div className="text-xs text-slate-500">Final Decision</div>
                        </div>
                    </div>

                    <hr className="divider" />

                    {/* Summary strip */}
                    <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                        {[
                            { label: "Risk Score", value: `${cam?.risk_score ?? "N/A"}/100` },
                            { label: "Loan Amount", value: formatCrore(cam?.recommended_loan_amount) },
                            { label: "Interest Rate", value: cam?.interest_rate ? `${cam.interest_rate}% p.a.` : "N/A" },
                            { label: "Tenor", value: cam?.loan_tenor_months ? `${cam.loan_tenor_months} months` : "N/A" },
                        ].map(({ label, value }) => (
                            <div key={label}>
                                <div className="text-xs text-slate-500">{label}</div>
                                <div className="text-base font-bold text-white mt-0.5">{value}</div>
                            </div>
                        ))}
                    </div>
                </div>
            </div>

            {/* CAM Sections */}
            {sections.map(({ title, content, icon: Icon }) => (
                <div key={title} className="glass rounded-xl overflow-hidden">
                    <div className="flex items-center gap-2.5 px-5 py-3.5 border-b border-white/5">
                        <Icon className="w-4 h-4 text-brand-400" />
                        <h2 className="text-sm font-bold text-white">{title}</h2>
                    </div>
                    <div className="p-5">
                        {content ? (
                            <pre className="text-sm text-slate-300 font-mono leading-relaxed whitespace-pre-wrap break-words">
                                {content}
                            </pre>
                        ) : (
                            <span className="text-sm text-slate-500 italic">No data available for this section.</span>
                        )}
                    </div>
                </div>
            ))}

            {/* Print hint */}
            <div className="text-center text-xs text-slate-600 pb-6">
                Use browser print (Ctrl+P) to save this report as PDF.
            </div>
        </div>
    );
}
